# Generated by Django 4.2.11 on 2024-03-28 05:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("student", "0002_remove_student_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="Resume",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("resume_file", models.FileField(upload_to="resumes/")),
            ],
        ),
    ]
